## Dog Breed Classification

In this project we will use traditional CNN, CNN with data augmentation and finally transfer Learning by VGG16 model with weights pre-trained on Imagenet to solve the dog breed classification problem

### Load Dataset Files

In [0]:
import tensorflow as tf

In [0]:
%tensorflow_version 2.x

In [3]:
import pandas as pd
import numpy as np
import tensorflow.keras
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense,Activation,Flatten
from tensorflow.keras.layers import Convolution2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input

#from keras.layers import Dense,Dropout,Input,MaxPooling2D,ZeroPadding2D,Conv2D,Flatten
#from keras.models import Sequential
from keras.losses import categorical_crossentropy
from keras.optimizers import Adam,SGD
from keras.preprocessing.image import img_to_array,load_img,ImageDataGenerator
from keras.utils import to_categorical

Using TensorFlow backend.


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


Now, upload the given dataset file shared with you in your google drive and give its path for the below given `project_path` variable. For example, a path is given below according to the file path in our google drive. You need to change this to match the path of yours.

In [0]:
project_path = "/content/drive/My Drive/AIML_Project/Dog_breed/"

Run the below code to extract all the images in the train.zip files given in the dataset. We are going to use these images as train and validation sets and their labels in further steps.

In [0]:
from zipfile import ZipFile
with ZipFile(project_path+'train.zip', 'r') as z:
  z.extractall()

Repeat the same step for test.zip

In [0]:
from zipfile import ZipFile
with ZipFile(project_path+'test.zip', 'r') as z:
  z.extractall()

Repeat the same step for sample_submission.csv.zip

In [0]:
from zipfile import ZipFile
with ZipFile(project_path+'sample_submission.csv.zip', 'r') as z:
  z.extractall()

Repeat the same step for labels.csv.zip

In [0]:
from zipfile import ZipFile
with ZipFile(project_path+'labels.csv.zip', 'r') as z:
  z.extractall()

After this process, we will have 4 files - Train folder, test folder and labels.csv and sample_submission.csv as part of your google drive

### Read labels.csv file using pandas

In [12]:
import numpy as np
import pandas as pd
labels_df=pd.read_csv("labels.csv")
print(labels_df.head())
sample_sub_df=pd.read_csv('sample_submission.csv')
sample_sub_df.head()

                                 id             breed
0  000bec180eb18c7604dcecc8fe0dba07       boston_bull
1  001513dfcb2ffafc82cccf4d8bbaba97             dingo
2  001cdf01b096e06d78e9e5112d419397          pekinese
3  00214f311d5d2247d5dfe4fe24b2303d          bluetick
4  0021f9ceb3235effd7fcde7f7538ed62  golden_retriever


id  ...  yorkshire_terrier
0  000621fb3cbb32d8935728e48679680e  ...           0.008333
1  00102ee9d8eb90812350685311fe5890  ...           0.008333
2  0012a730dfa437f5f3613fb75efcd4ce  ...           0.008333
3  001510bc8570bbeee98c8d80c8a95ec1  ...           0.008333
4  001a5f3114548acdefa3d4da05474c2e  ...           0.008333

[5 rows x 121 columns]

### Print the count of each category of Dogs given in the dataset



In [13]:
labels_df.groupby(["breed"]).count()


id
breed                              
affenpinscher                    80
afghan_hound                    116
african_hunting_dog              86
airedale                        107
american_staffordshire_terrier   74
...                             ...
welsh_springer_spaniel           79
west_highland_white_terrier      81
whippet                          95
wire-haired_fox_terrier          82
yorkshire_terrier                82

[120 rows x 1 columns]

### Get one-hot encodings of labels

In [14]:
img_label=pd.get_dummies(labels_df.breed)
img_label.head()

affenpinscher  afghan_hound  ...  wire-haired_fox_terrier  yorkshire_terrier
0              0             0  ...                        0                  0
1              0             0  ...                        0                  0
2              0             0  ...                        0                  0
3              0             0  ...                        0                  0
4              0             0  ...                        0                  0

[5 rows x 120 columns]

## Preparing training dataset
1. Write a code which reads each and every id from labels.csv file and loads the corresponding image (in RGB - 128, 128, 3) from the train folder. <br>
2. Create 2 variables <br> 
     a.  x_train - Should have all the images of the dogs from train folder <br>
     b.  y_train - Corresponding label of the dog <br>
<u>Note:</u> The id of the dog images and its corresponding labels are available in labels.csv file   
<u>Hint:</u> Watch the video shared on "Preparing the training dataset" if you face issue on creating the training dataset

In [0]:
img_rows=128
img_cols=128
num_channels=1

In [16]:
import matplotlib.pyplot as plt
from skimage.transform import resize
from tqdm import tqdm
x_train=[]
y_train=[]
for f,img in tqdm(labels_df.values):
    train_img=plt.imread('./train/{}.jpg'.format(f),1)
    train_img_resize=resize(train_img,(img_rows,img_cols))
    x_train.append(train_img_resize)
    y_train.append(img)
    type(x_train)

100%|██████████| 10222/10222 [04:33<00:00, 37.41it/s]


In [0]:
type(train_img)

numpy.ndarray

In [0]:
type(x_train)

list

In [0]:
# Read the image
plt.imshow(x_train[1])
print(y_train[1])
plt.show()

In [0]:
path='./train/'

In [0]:
new_df=labels_df.assign(img_path=lambda x: path + labels_df['id'] +'.jpg')

In [19]:
new_df.head()

id  ...                                      img_path
0  000bec180eb18c7604dcecc8fe0dba07  ...  ./train/000bec180eb18c7604dcecc8fe0dba07.jpg
1  001513dfcb2ffafc82cccf4d8bbaba97  ...  ./train/001513dfcb2ffafc82cccf4d8bbaba97.jpg
2  001cdf01b096e06d78e9e5112d419397  ...  ./train/001cdf01b096e06d78e9e5112d419397.jpg
3  00214f311d5d2247d5dfe4fe24b2303d  ...  ./train/00214f311d5d2247d5dfe4fe24b2303d.jpg
4  0021f9ceb3235effd7fcde7f7538ed62  ...  ./train/0021f9ceb3235effd7fcde7f7538ed62.jpg

[5 rows x 3 columns]

In [20]:
new_df.shape

(10222, 3)

In [21]:
import numpy as np

img_pixel=np.array([img_to_array(load_img(img, target_size=(128, 128))) for img in tqdm(new_df['img_path'].values.tolist())])


100%|██████████| 10222/10222 [00:33<00:00, 302.53it/s]


In [0]:
img_pixel.shape

(10222, 128, 128, 3)

Normalize the training data and convert into 4 dimensions so that it can be used as an input to conv layers in the model

In [22]:
#Normalizing the input
x_train_data=img_pixel
x_train_data/=255
y_train_data=img_label.values
print(x_train_data.shape)
print(y_train_data.shape)


(10222, 128, 128, 3)
(10222, 120)


### Split the training and validation data from `x_train_data` and `y_train_data` obtained from above step

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_train_data,y_train_data,test_size=0.2)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8177, 128, 128, 3)
(8177, 120)
(2045, 128, 128, 3)
(2045, 120)


### Loading the test data
Read the id column from the samples_submission.csv and store it in test_img

In [0]:
test_img =sample_sub_df["id"]
print(test_img)

0        000621fb3cbb32d8935728e48679680e
1        00102ee9d8eb90812350685311fe5890
2        0012a730dfa437f5f3613fb75efcd4ce
3        001510bc8570bbeee98c8d80c8a95ec1
4        001a5f3114548acdefa3d4da05474c2e
                       ...               
10352    ffeda8623d4eee33c6d1156a2ecbfcf8
10353    fff1ec9e6e413275984966f745a313b0
10354    fff74b59b758bbbf13a5793182a9bbe4
10355    fff7d50d848e8014ac1e9172dc6762a3
10356    fffbff22c1f51e3dc80c4bf04089545b
Name: id, Length: 10357, dtype: object


Run the below code to load the test image files in x_test_feature

In [0]:
x_test_feature = []
import matplotlib.pyplot as plt
from skimage.transform import resize
from tqdm import tqdm
i = 0 # initialisation
for f in tqdm(test_img.values): # f for format ,jpg
    img = plt.imread('./test/{}.jpg'.format(f), 0)
    img_resize = resize(img, (img_rows, img_cols)) 
    x_test_feature.append(img_resize)

100%|██████████| 10357/10357 [04:15<00:00, 40.55it/s]


In [0]:
test_path='./test/'

In [0]:
test_df=sample_sub_df.assign(img_path=lambda x: test_path + sample_sub_df['id'] +'.jpg')

In [0]:
test_df.head()

id  ...                                     img_path
0  000621fb3cbb32d8935728e48679680e  ...  ./test/000621fb3cbb32d8935728e48679680e.jpg
1  00102ee9d8eb90812350685311fe5890  ...  ./test/00102ee9d8eb90812350685311fe5890.jpg
2  0012a730dfa437f5f3613fb75efcd4ce  ...  ./test/0012a730dfa437f5f3613fb75efcd4ce.jpg
3  001510bc8570bbeee98c8d80c8a95ec1  ...  ./test/001510bc8570bbeee98c8d80c8a95ec1.jpg
4  001a5f3114548acdefa3d4da05474c2e  ...  ./test/001a5f3114548acdefa3d4da05474c2e.jpg

[5 rows x 122 columns]

Normalize the test data and convert it into 4 dimensions

In [0]:
img_pixel=np.array([img_to_array(load_img(img, target_size=(128, 128))) for img in tqdm(test_df['img_path'].values.tolist())])



100%|██████████| 10357/10357 [00:33<00:00, 309.86it/s]


In [0]:
y_test_data=pd.get_dummies(test_df)

In [0]:
#Normalizing the input
x_test_data=img_pixel
x_test_data/=255
#y_test_data=test_df.breed
print(x_test_data.shape)
print(y_test_data.shape)

(10357, 128, 128, 3)
(10357, 20834)


### Build a basic conv neural network with 2 conv layers (kernel sizes - 5 and 3) add layers as mentioned below for classification.

1. Add a Dense layer with 256 neurons with `relu` activation

2. Add a Dense layer with 120 neurons as final layer (as there are 120 classes in the given dataset) with `softmax` activation for classifiaction. 

In [0]:
#import keras
#from keras.models import Sequential,Input,Model
#from keras.layers import Dense, Dropout, Flatten
#from keras.layers import Conv2D, MaxPooling2D
#from keras.layers.normalization import BatchNormalization


In [0]:

model = Sequential()
# 1st Conv Layer
model.add(Convolution2D(32, (5, 5),activation='relu', input_shape=(128, 128, 3)))

# 2nd Conv Layer
model.add(Convolution2D(32, (3, 3),activation='relu'))

# Adds a densely-connected layer with 256 units to the model:
model.add(Flatten()) # Stretching the volume to 256.
model.add(Dense(256, activation='relu'))

# Add an output layer with 120 output units:
model.add(Dense(120, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
early_stopping = tensorflow.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, verbose=1, mode='auto')
callback_list = [early_stopping]

In [0]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 124, 124, 32)      2432      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 122, 122, 32)      9248      
_________________________________________________________________
flatten_1 (Flatten)          (None, 476288)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               121929984 
_________________________________________________________________
dense_2 (Dense)              (None, 120)               30840     
Total params: 121,972,504
Trainable params: 121,972,504
Non-trainable params: 0
_________________________________________________________________


### Use batch_size = 128 and epochs = 10 and execute the model

In [0]:
batch_size=128
epochs=10
num_classes=120

In [29]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8177, 128, 128, 3)
(8177, 120)
(2045, 128, 128, 3)
(2045, 120)


In [30]:
dog_model = model.fit(X_train, y_train, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(X_test, y_test))


Epoch 1/10
64/64 [==============================] - 5s 84ms/step - loss: 0.0156 - accuracy: 0.9994 - val_loss: 8.8872 - val_accuracy: 0.0249
Epoch 2/10
64/64 [==============================] - 5s 84ms/step - loss: 0.0164 - accuracy: 0.9991 - val_loss: 8.6133 - val_accuracy: 0.0259
Epoch 3/10
64/64 [==============================] - 5s 84ms/step - loss: 0.0104 - accuracy: 0.9994 - val_loss: 9.0824 - val_accuracy: 0.0284
Epoch 4/10
64/64 [==============================] - 5s 85ms/step - loss: 0.0086 - accuracy: 0.9993 - val_loss: 8.8200 - val_accuracy: 0.0289
Epoch 5/10
64/64 [==============================] - 5s 85ms/step - loss: 0.0090 - accuracy: 0.9995 - val_loss: 8.4820 - val_accuracy: 0.0264
Epoch 6/10
64/64 [==============================] - 5s 84ms/step - loss: 0.0097 - accuracy: 0.9991 - val_loss: 11.1069 - val_accuracy: 0.0289
Epoch 7/10
64/64 [==============================] - 5s 84ms/step - loss: 0.0080 - accuracy: 0.9994 - val_loss: 10.1949 - val_accuracy: 0.0289
Epoch 8/10


#The model accuracy is very poor !!!!

### Use Data Augmentation in the above model to see if the accuracy improves


In [0]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input

### Using the above objects, create the image generators with variable names `train_generator` and `val_generator`

You need to use train_datagen.flow() and val_datagen.flow()

In [32]:
# This will do preprocessing and realtime data augmentation:
train_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input, 
    zca_whitening=True,  # apply ZCA whitening
    rotation_range=50,  # randomly rotate images in the range (degrees, 0 to 180)
    width_shift_range=0.2,  # randomly shift images horizontally (fraction of total width)
    height_shift_range=0.2,  # randomly shift images vertically (fraction of total height)
    horizontal_flip=True)  # randomly flip images

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py:336: UserWarning: This ImageDataGenerator specifies `zca_whitening`, which overrides setting of `featurewise_center`.
  warnings.warn('This ImageDataGenerator specifies '


In [33]:
# This will do preprocessing and realtime data augmentation:
val_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input, 
    zca_whitening=True,  # apply ZCA whitening
    rotation_range=50,  # randomly rotate images in the range (degrees, 0 to 180)
    width_shift_range=0.2,  # randomly shift images horizontally (fraction of total width)
    height_shift_range=0.2,  # randomly shift images vertically (fraction of total height)
    horizontal_flip=True)  # randomly flip images

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py:336: UserWarning: This ImageDataGenerator specifies `zca_whitening`, which overrides setting of `featurewise_center`.
  warnings.warn('This ImageDataGenerator specifies '


### Fit the model using fit_generator() using `train_generator` and `val_generator` from the above step with 10 epochs

In [0]:
early_stopping = tensorflow.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, verbose=1, mode='auto')
callback_list = [early_stopping]

# This model is taking more than an hour for one Epoch. One of the runs has completed one Epoch with an accuracy of .018. Hence this is aborted manually.

In [0]:
model.fit_generator(train_generator.flow(X_train, y_train,batch_size=batch_size),
                    epochs=5,
                    validation_data=val_generator.flow(X_test, y_test,batch_size=batch_size), callbacks=callback_list)

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py:716: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py:735: UserWarning: This ImageDataGenerator specifies `zca_whitening`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '


Epoch 1/5
   3735/Unknown - 1823s 488ms/step - loss: 4.7749 - accuracy: 0.0117

# Model accuracy is still poor!!!

### Lets use Transfer Learning

Download the vgg wieght file from here : https://github.com/MinerKasch/applied_deep_learning/blob/master/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

Use the below code to load VGG16 weights trained on ImageNet

In [0]:
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
# Instantiate the model with the pre-trained weights (no top)
base_model= VGG16(weights=(project_path+'vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'),
                 include_top=False, pooling='avg',input_shape = (128, 128, 3))

Print the summary of the base_model

In [38]:
base_model.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 128, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 128, 128, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 128, 128, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 64, 64, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 64, 64, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 64, 64, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 32, 32, 128)       0     

### Add the following classification layers to the imported VGG Model <br>
1. Flatten Layer
2. Dense layer with 1024 neurons with activation as Relu
3. Dense layer with 256 neurons with activation as Relu
4. Dense layer with 120 neurons with activation as Softmax

In [0]:
#Adding custom Layers 
Model1 = base_model.output

#Flatten layer
Model2 = Flatten()(Model1)

# Adds a densely-connected layer with 1024 units to the model:
Model2 = Dense(1024,activation = 'relu')(Model2)

#Adds a densely-connected layer with 256 units to the model:
Model2 = Dense(256,activation = 'relu')(Model2)

# Add an output layer with 120 output units:
pred = Dense(120,activation = 'softmax')(Model2)


# creating the final model 
Trans_Model1 = Model(base_model.input,pred)

# Loss and Optimizer

  

### Make all the layers in the base_model (VGG16) to be non-trainable

In [42]:
#Freezing layers in the model which don't have 'dense' in their name
for layer in base_model.layers:
  if('conv' in layer.name): #prefix detection to freeze layers which does not have dense
    #Freezing a layer
    layer.trainable = False

#Module to print colourful statements
from termcolor import colored

#Check which layers have been frozen 
for layer in base_model.layers:
  print (colored(layer.name, 'blue'))
  print (colored(layer.trainable, 'red'))

input_1
True
block1_conv1
False
block1_conv2
False
block1_pool
True
block2_conv1
False
block2_conv2
False
block2_pool
True
block3_conv1
False
block3_conv2
False
block3_conv3
False
block3_pool
True
block4_conv1
False
block4_conv2
False
block4_conv3
False
block4_pool
True
block5_conv1
False
block5_conv2
False
block5_conv3
False
block5_pool
True
global_average_pooling2d
True


### Fit and compile the model with batch_size = 128 and epochs = 10 and execute the model

Try to get training and validation accuracy to be more than 90%

In [0]:
  # Loss and Optimizer
 Trans_Model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#base_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
Trans_Model1.fit(X_train, y_train, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(X_test, y_test))

Train on 8177 samples, validate on 2045 samples
Epoch 1/10
8177/8177 [==============================] - 4s 444us/step - loss: 4.7866 - acc: 0.0120 - val_loss: 4.7865 - val_acc: 0.0112
Epoch 2/10
8177/8177 [==============================] - 2s 305us/step - loss: 4.7807 - acc: 0.0126 - val_loss: 4.7878 - val_acc: 0.0112
Epoch 3/10
8177/8177 [==============================] - 3s 306us/step - loss: 4.7776 - acc: 0.0126 - val_loss: 4.7883 - val_acc: 0.0112
Epoch 4/10
8177/8177 [==============================] - 3s 307us/step - loss: 4.7767 - acc: 0.0126 - val_loss: 4.7910 - val_acc: 0.0112
Epoch 5/10
8177/8177 [==============================] - 3s 309us/step - loss: 4.7765 - acc: 0.0126 - val_loss: 4.7894 - val_acc: 0.0112
Epoch 6/10
8177/8177 [==============================] - 3s 310us/step - loss: 4.7758 - acc: 0.0126 - val_loss: 4.7913 - val_acc: 0.0112
Epoch 7/10
8177/8177 [==============================] - 3s 311us/step - loss: 4.7759 - acc: 0.0126 - val_loss: 4.7901 - val_acc: 0.0112


In [44]:
Trans_Model1.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 128, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 128, 128, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 128, 128, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 64, 64, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 64, 64, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 64, 64, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 32, 32, 128)       0     